fix: move ramda types to production dependencies
In commit https://github.com/cypress-io/schema-tools/commit/8a667a283d37bf3e6401cb114051dc39838de064
we have started including ".d.ts" files with NPM package, which
generate comment `/// <reference types="ramda" />` which needs
TS definitions for Ramda library. So we must include the
`@types/ramda` in production dependencies, otherwise anyone using
our types from ".d.ts" gets missing type error like this one:

```
node_modules/@cypress/schema-tools/dist/api.d.ts:1:23
error TS2688: Cannot find type definition file for 'ramda'.
1 /// <reference types="ramda" />
```